Repository Sasafrass/straattaal, pull requests merged in 2021-07, with the labels that each got.

#20 Rewrite training and inference code to more modern pytorch, add some functionalities and models
  app/api/slang.py
  app/auth/routes.py
  app/main/forms.py
  app/main/routes.py
  app/ml_models/rnn/2021_straattaal_epoch100.pt
  app/ml_models/rnn/2021_straattaal_epoch200.pt
  app/ml_models/rnn/data_tools.py
  app/ml_models/rnn/file_readers.py
  app/ml_models/rnn/generate.py
  app/ml_models/rnn/loaded_rnn_model.py
  app/ml_models/rnn/pretrained_dutch_epoch3.pt
  app/ml_models/rnn/rnn_model.py
  app/ml_models/rnn/train.py
  data/dutch.txt
  data/vocabulary.txt
  generate.ipynb
  train.ipynb
Labels: enhancement

#19 Implement groups model and update index.html accordingly
  app/__init__.py
  app/groups/__init__.py
  app/groups/forms.py
  app/groups/routes.py
  app/groups/static/style.css
  app/ml_models/rnn/generate.py
  app/models.py
  app/templates/base.html
  app/templates/groups/create.html
  app/templates/groups/main.html
  app/templates/index.html
  config.py
  migrations/env.py
  migrations/versions/3622b1ed7dfb_slang_table.py
  migrations/versions/79bf0dddc7f6_users_table.py
  migrations/versions/c2b12030531b_add_groups_model_to_database.py
  migrations/versions/c331041334ca_slang_table.py
  straattaal.py
Labels: bug, enhancement, help wanted

#39 Add server-side session management with Flask-Session.
  .gitignore
  app/__init__.py
  app/main/routes.py
  requirements.txt
Labels: enhancement

#35 Word meaning
  .gitignore
  app/__init__.py
  app/main/forms.py
  app/main/routes.py
  app/templates/index.html
  requirements.txt
Labels: enhancement, good first issue

#38 Add vocabulary object. Model loading infers RNN size.
  app/api/slang.py
  app/ml_models/rnn/data_tools.py
  app/ml_models/rnn/generate.py
  app/ml_models/rnn/loaded_rnn_model.py
  app/ml_models/rnn/rnn_model.py
  app/ml_models/rnn/train.py
  app/ml_models/rnn/vocabulary.py
  generate.ipynb
Labels: enhancement

#47 Run black linter for full project.
  app/main/routes.py
  app/ml_models/rnn/vocabulary.py
  app/users/routes.py
Labels: Refactor

#49 Create notebooks directory and move notebooks there. Remove legacy notebook
  app/ml_models/rnn/2337-26062021_model.pth
  app/ml_models/rnn/loaded_rnn_model.py
  app/ml_models/rnn/pretrained/2019-11072021_straattaal.pth
  app/ml_models/rnn/pretrained/2021_straattaal_epoch100.pt
  app/ml_models/rnn/pretrained/2021_straattaal_epoch200.pt
  app/ml_models/rnn/pretrained/pretrained_dutch_epoch3.pt
  app/ml_models/rnn/train.py
  generate.ipynb
  notebooks/generate.ipynb
  notebooks/train.ipynb
  rnn_generator.ipynb
  train.ipynb
Labels: Refactor

#48 Initial docstring updates.
  app/__init__.py
  app/api/__init__.py
  app/api/slang.py
  app/api/users.py
  app/auth/__init__.py
  app/auth/forms.py
  app/auth/routes.py
  app/groups/__init__.py
  app/groups/forms.py
  app/groups/routes.py
  app/main/__init__.py
  app/main/forms.py
  app/main/routes.py
  app/ml_models/rnn/data_tools.py
  app/ml_models/rnn/file_readers.py
  app/ml_models/rnn/generate.py
  app/ml_models/rnn/helpers.py
  app/ml_models/rnn/loaded_rnn_model.py
  app/ml_models/rnn/rnn_model.py
  app/ml_models/rnn/train.py
  app/ml_models/rnn/vocabulary.py
  app/models.py
  app/users/__init__.py
  app/users/forms.py
  app/users/routes.py
  config.py
  straattaal.py
Labels: Refactor, documentation, help wanted

#53 Create a 10px margin in the new /app/static/style.css
  app/static/style.css
  app/templates/base.html
Labels: Frontend, enhancement

#52 Implement internal call so we can load model from session.
  app/api/slang.py
  app/main/routes.py
Labels: Refactor, enhancement, performance

#58 Update docstring: amount to number (of words).
  app/ml_models/rnn/data_tools.py
Labels: Refactor, documentation

#61 Update favorite words + meanings.
  README.md
Labels: documentation, good first issue

#62 Argparse
  .gitignore
  app/ml_models/rnn/loaded_rnn_model.py
  app/ml_models/rnn/train.py
  app/ml_models/rnn/vocabulary.py
  requirements.txt
  train_wrapper.py
Labels: Refactor, enhancement, good first issue

#64 Dropdown model selector
  app/api/slang.py
  app/main/forms.py
  app/main/routes.py
  app/models.py
  app/templates/index.html
  app/users/routes.py
  migrations/versions/990d4ed9bb61_add_type_of_word_to_word_table.py
  straattaal.py
Labels: Work In Progress, enhancement

#70 Fix Sqlite bug with ALTER in flask db upgrade files.
  app/__init__.py
Labels: bug, invalid
